name: My Workflow

on: [push]

jobs:
  runMultipleCommands:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1
     - run: |
          sudo mkdir test1
          sudo cd test1
          git clone git@github.com:premguna/test.git
          cd test
          git pull origin main
          
      
       
    
    
     - run: echo "One last message"
           
           
           
        
     
       
      


         
     
      
                   
              
