name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
      
  Deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
    run: |
       echo "$PRIVATE_KEY" > private_key
       sudo chmod 600 private_key
       sudo scp -i private_key -r * StrictHostKeyChecking=no ${USER_NAME}@${HOSTNAME}:/home/ec2-user/testing/guna
       
      
    env:
            PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
            HOSTNAME : ${{ secrets.HOSTNAME  }}
            USER_NAME : ${{ secrets.USER_NAME  }}
            source: "*"
            port: 22
            target: "/home/ec2-user/testing/guna"
         
     
      
                   
              
