name: My Workflow

on: [push]

jobs:
  runMultipleCommands:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1
     - name: login to ec2
       env:
          PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
          HOSTNAME : ${{ secrets.HOSTNAME  }}
          USER_NAME : ${{ secrets.USER_NAME  }}
          port: 22
          
     - name: deploy     
     - run: |
          echo "$PRIVATE_KEY" > private_key
          sudo chmod 600 private_key
          sudo ssh -i private_key StrictHostKeyChecking=no ${USER_NAME}@${HOSTNAME}
          touch /home/ec2-user/hghgh
          
      
       
    
    
    
           
           
           
        
     
       
      


         
     
      
                   
              
