name: CI/CD 

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

  Deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
            HOSTNAME : ${{ secrets.HOSTNAME  }}
            USER_NAME : ${{ secrets.USER_NAME  }}
            
        run: |
            
            'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
             eval $(ssh-agent -s)
             echo "$SSH_KEY_PRODUCTION" | tr -d '\r' | ssh-add -
             mkdir -p ~/.ssh
             chmod 700 ~/.ssh
             echo "$SSH_KEY_PRODUCTION" > ~/.ssh/test
            '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
             chmod 700 ~/.ssh/test

            mkdir tester
            cd tester
            git checkout main 
            git fetch --all 
            git pull origin main 
            
            echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
            scp -r test/* -i private_key ${USER_NAME}@${HOSTNAME}:/home/ec2-user/testing/.
            
            
