name: My Workflow

on: [push]

jobs:
  runMultipleCommands:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1
     - run: |
        echo "A initial message"
        command -v ssh-agent >/dev/null 
        apt-get update -y && apt-get install openssh-client -y
        eval $(ssh-agent -s)
        echo "$AWS_PRIVATE_KEY" | tr -d '\r' | ssh-add -
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        apt-get install yarn -qy
        yarn global add @gridsome/cli
        cd gridsome
        yarn install
    
    
     - run: echo "One last message"
           
           
           
        
     
       
      


         
     
      
                   
              
