name: scp files
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOSTNAME }}
        username: ${{ secrets.USER_NAME }}
        private_key: ${{ secrets.AWS_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        source: "test/a.txt,test/b.txt"
        target: "test"
